<a href="https://colab.research.google.com/github/Dr-Isam-ALJAWARNEH/fds-project-space-time-clustering-for-aq/blob/main/Visualize_before_sampling_Chicago_Space_Time_Clustering_of_Mobility_Patterns_and_Air_Quality_Hotspots.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Project Title: Space-Time Clustering of Mobility Patterns and Air Quality Hotspots for Chicago**

Creating pollution category to visualize

In [ ]:
joined_sorted #final joined cleaned table

,geohash,time_bin,pickup_trip_count,dropoff_trip_count,total_trip_count,Temperature,Humidity,PM25,CO,latitude,longitude,geometry,index_right,community
14289,dp3wq0,2021-09-23 18:00:00,84.0,72.0,156.0,18.219515,48.329417,3.119984,-8.763366,41.882629,-87.621460,POINT (-87.62146 41.88263),37.0,LOOP
14446,dp3wq0,2021-10-08 16:00:00,78.0,66.0,144.0,22.041588,74.874878,7.541146,-8.772865,41.882629,-87.621460,POINT (-87.62146 41.88263),37.0,LOOP
14438,dp3wq0,2021-10-07 18:00:00,80.0,62.0,142.0,20.956601,87.691151,13.242789,-8.771948,41.882629,-87.621460,POINT (-87.62146 41.88263),37.0,LOOP
14432,dp3wq0,2021-10-06 18:00:00,73.0,69.0,142.0,20.543289,81.053314,16.962333,-8.772314,41.882629,-87.621460,POINT (-87.62146 41.88263),37.0,LOOP
14268,dp3wq0,2021-09-22 18:00:00,73.0,68.0,141.0,17.558538,67.523055,2.077877,-8.763452,41.882629,-87.621460,POINT (-87.62146 41.88263),37.0,LOOP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2184,dp3ttt,2021-07-28 07:00:00,0.0,1.0,1.0,26.568171,69.099808,10.935176,0.324532,41.778259,-87.643433,POINT (-87.64343 41.77826),65.0,ENGLEWOOD
2308,dp3ttt,2021-08-04 12:00:00,1.0,0.0,1.0,21.310779,69.789401,19.572630,0.639387,41.778259,-87.643433,POINT (-87.64343 41.77826),65.0,ENGLEWOOD
7879,dp3we8,2021-09-27 23:00:00,0.0,1.0,1.0,20.798811,69.980136,8.157049,0.177400,41.926575,-87.731323,POINT (-87.73132 41.92657),20.0,HERMOSA
835,dp3trw,2021-08-19 22:00:00,0.0,1.0,1.0,33.707631,57.877986,6.610062,0.197740,41.739807,-87.555542,POINT (-87.55554 41.73981),41.0,SOUTH CHICAGO
14624,dp3wtd,2021-09-19 13:00:00,1.0,0.0,1.0,23.554063,72.146953,6.619960,0.272133,41.937561,-87.643433,POINT (-87.64343 41.93756),44.0,LAKE VIEW

In [ ]:
def categorize_pm25(pm):
    if pm <= 12.0:
        return 'Low'
    elif pm <= 35.4:
        return 'Medium'
    else:
        return 'High'

In [ ]:
# Apply to table
joined_sorted['pollution_category'] = joined_sorted['PM25'].apply(categorize_pm25)

# Preview
joined_sorted[['PM25', 'pollution_category']].head()

            PM25 pollution_category
14289   3.119984                Low
14446   7.541146                Low
14438  13.242789             Medium
14432  16.962333             Medium
14268   2.077877                Low

In [ ]:
# Show the full table with the new pollution category column
joined_sorted[['geohash', 'time_bin', 'pickup_trip_count', 'dropoff_trip_count', 'total_trip_count',
               'Temperature', 'Humidity', 'PM25', 'pollution_category', 'CO', 'latitude', 'longitude',
               'geometry', 'index_right', 'community']].head(20)

,geohash,time_bin,pickup_trip_count,dropoff_trip_count,total_trip_count,Temperature,Humidity,PM25,pollution_category,CO,latitude,longitude,geometry,index_right,community
14289,dp3wq0,2021-09-23 18:00:00,84.0,72.0,156.0,18.219515,48.329417,3.119984,Low,-8.763366,41.882629,-87.62146,POINT (-87.62146 41.88263),37.0,LOOP
14446,dp3wq0,2021-10-08 16:00:00,78.0,66.0,144.0,22.041588,74.874878,7.541146,Low,-8.772865,41.882629,-87.62146,POINT (-87.62146 41.88263),37.0,LOOP
14438,dp3wq0,2021-10-07 18:00:00,80.0,62.0,142.0,20.956601,87.691151,13.242789,Medium,-8.771948,41.882629,-87.62146,POINT (-87.62146 41.88263),37.0,LOOP
14432,dp3wq0,2021-10-06 18:00:00,73.0,69.0,142.0,20.543289,81.053314,16.962333,Medium,-8.772314,41.882629,-87.62146,POINT (-87.62146 41.88263),37.0,LOOP
14268,dp3wq0,2021-09-22 18:00:00,73.0,68.0,141.0,17.558538,67.523055,2.077877,Low,-8.763452,41.882629,-87.62146,POINT (-87.62146 41.88263),37.0,LOOP
14445,dp3wq0,2021-10-08 15:00:00,76.0,60.0,136.0,21.811943,77.052307,9.092063,Low,-8.772517,41.882629,-87.62146,POINT (-87.62146 41.88263),37.0,LOOP
14308,dp3wq0,2021-09-24 16:00:00,68.0,67.0,135.0,21.196887,47.283936,3.450944,Low,-8.762341,41.882629,-87.62146,POINT (-87.62146 41.88263),37.0,LOOP
14449,dp3wq0,2021-10-08 19:00:00,58.0,76.0,134.0,22.425575,75.372314,8.628258,Low,-8.764925,41.882629,-87.62146,POINT (-87.62146 41.88263),37.0,LOOP
14309,dp3wq0,2021-09-24 17:00:00,65.0,69.0,134.0,22.654662,46.133562,5.581311,Low,-8.761863,41.882629,-87.62146,POINT (-87.62146 41.88263),37.0,LOOP
14158,dp3wq0,2021-09-17 14:00:00,75.0,59.0,134.0,24.072342,70.731990,13.128645,Medium,-8.761499,41.882629,-87.62146,POINT (-87.62146 41.88263),37.0,LOOP
14288,dp3wq0,2021-09-23 17:00:00,67.0,67.0,134.0,17.605349,51.108424,3.035889,Low,-8.763929,41.882629,-87.62146,POINT (-87.62146 41.88263),37.0,LOOP
14307,dp3wq0,2021-09-24 15:00:00,72.0,60.0,132.0,19.840178,48.008451,4.017532,Low,-8.762223,41.882629,-87.62146,POINT (-87.62146 41.88263),37.0,LOOP
14310,dp3wq0,2021-09-24 18:00:00,65.0,66.0,131.0,24.040298,45.214335,7.197949,Low,-8.760700,41.882629,-87.62146,POINT (-87.62146 41.88263),37.0,LOOP
13578,dp3wq0,2021-08-20 19:00:00,64.0,67.0,131.0,28.693397,70.784690,19.944073,Medium,-10.961180,41.882629,-87.62146,POINT (-87.62146 41.88263),37.0,LOOP
13867,dp3wq0,2021-09-03 15:00:00,64.0,66.0,130.0,23.847370,56.769307,4.410244,Low,-8.761513,41.882629,-87.62146,POINT (-87.62146 41.88263),37.0,LOOP
14389,dp3wq0,2021-10-01 16:00:00,70.0,58.0,128.0,23.494670,64.687729,7.281241,Low,-8.774400,41.882629,-87.62146,POINT (-87.62146 41.88263),37.0,LOOP
14304,dp3wq0,2021-09-24 12:00:00,64.0,61.0,125.0,16.764492,53.259416,4.755784,Low,-8.764487,41.882629,-87.62146,POINT (-87.62146 41.88263),37.0,LOOP
12716,dp3wq0,2021-07-09 18:00:00,66.0,59.0,125.0,22.112350,62.558954,2.606029,Low,-8.762713,41.882629,-87.62146,POINT (-87.62146 41.88263),37.0,LOOP
13870,dp3wq0,2021-09-03 18:00:00,63.0,61.0,124.0,25.010058,55.216853,7.612714,Low,-8.760295,41.882629,-87.62146,POINT (-87.62146 41.88263),37.0,LOOP
14378,dp3wq0,2021-09-30 18:00:00,68.0,55.0,123.0,22.042255,59.089788,4.917158,Low,-8.763935,41.882629,-87.62146,POINT (-87.62146 41.88263),37.0,LOOP

In [ ]:
import folium
from folium.plugins import MarkerCluster

In [ ]:
# Center map over Chicago
chicago_center = [41.8781, -87.6298]
m = folium.Map(location=chicago_center, zoom_start=11)

In [ ]:
# Set colors for different pollution levels
color_dict = {
    'Low': 'green',
    'Medium': 'orange',
    'High': 'red'
}

In [ ]:
# Create a cluster layer
marker_cluster = MarkerCluster().add_to(m)

# Loop through your FULL joined_sorted data
for idx, row in joined_sorted.iterrows():
    folium.CircleMarker(
        location=[row['latitude'], row['longitude']],
        radius=4,
        color=color_dict.get(row['pollution_category'], 'blue'),
        fill=True,
        fill_color=color_dict.get(row['pollution_category'], 'blue'),
        fill_opacity=0.7,
        popup=(f"PM2.5: {row['PM25']:.2f}\n"
               f"Trips: {row['total_trip_count']}")
    ).add_to(marker_cluster)

# Display the map
m